# Generated by Django 4.2.4 on 2023-08-15 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bot_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstate",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="bot_app.user"
            ),
        ),
    ]
